sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  redis:
      host: localhost
      port: 6379
#      password:
      database: 10
  wechat:
    appid: wxf0c0c0c0c0c0c0c0
    secret: 123456

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tPeFLzsPPT8gG3LPW64
    access-key-secret: U6k1brOZ8gaOIXv3NXbulGTUzy6Pd7
    bucket-name: sky-itcast

# 注意：file 节点要放在 sky 节点外面，作为根节点
file:
  upload:
    base-dir: E:/temp/sky/upload  # 本地存储目录（Windows示例）
    # base-dir: /usr/local/sky/upload  # Linux示例
    access-path: /upload  # 对外访问的路径前缀

# 文件上传大小限制（核心配置）
spring:
  servlet:
    multipart:
      max-file-size: 2MB  # 单个文件最大限制（2MB）
      max-request-size: 6MB  # 单次请求最大限制（若上传多个文件，总和不超过此值）

# 服务器地址拼接
server:
  url: http://127.0.0.1:8080
