server:
  port: ${server.port}
  url: ${server.url}

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${sky.datasource.driver-class-name}
      url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${sky.datasource.username}
      password: ${sky.datasource.password}
  redis:
      host: ${sky.redis.host}
      port: ${sky.redis.port}
#      password: ${sky.redis.password}
      database: ${sky.redis.database}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: ${sky.jwt.admin-secret-key}
    # 设置jwt过期时间
    admin-ttl: ${sky.jwt.admin-ttl}
    # 设置前端传递过来的令牌名称
    admin-token-name: ${sky.jwt.admin-token-name}
    user-secret-key: ${sky.jwt.user-secret-key}
    user-ttl: ${sky.jwt.user-ttl}
    user-token-name: ${sky.jwt.user-token-name}
  alioss:
    endpoint: ${sky.alioss.endpoint}
    access-key-id: ${sky.alioss.access-key-id}
    access-key-secret: ${sky.alioss.access-key-secret}
    bucket-name: ${sky.alioss.bucket-name}
  wechat:
    appid: ${sky.wechat.appid}
    secret: ${sky.wechat.secret}
    mch-id: ${sky.wechat.mch-id}
    mch-serial-no: ${sky.wechat.mch-serial-no}
    private-key-path: ${sky.wechat.private-key-path}
    api-v3-key: ${sky.wechat.api-v3-key}
    we-chat-pay-cert-file-path: ${sky.wechat.we-chat-pay-cert-file-path}
    notify-url: ${sky.wechat.notify-url}
    refund-notify-url: ${sky.wechat.refund-notify-url}

  shop:
    address: ${sky.shop.address}
  baidu:
    ak: ${sky.baidu.ak}

file:
  upload:
    base-dir: ${file.upload.base-dir}
    access-path: ${file.upload.access-path}

